export class UserEntity {
  constructor(
    public usr_idt_id: number,
    public loc_idt_id: number,
    public usr_txt_name: string,
    public usr_txt_lastname: string,
    public usr_txt_dni: string,
    public usr_dat_dateofbirth: Date,
    public usr_int_gender: number,
    public usr_txt_celphone: string | null,
    public usr_txt_cuit_cuil: string,
    public usr_txt_email: string,
    public usr_txt_streetname: string,
    public usr_txt_streetnumber: string,
    public usr_txt_floor: string | null,
    public usr_txt_department: string | null,
    public usr_txt_postalcode: string,
    public usr_int_rol: number,
    public usr_dat_registrationdate: Date,
    public usr_int_registerorigin: number,
    public usr_txt_registeroriginhash: string | null,
    public usr_dat_terminationdate: Date | null,
    public usr_int_image: number | null,
    public usr_txt_image_ext: string | null,
    public usr_txt_password: string | null,
    public usr_txt_token: string | null,
    public usr_sta_state: number,
    public usr_sta_employee_state: number,
    public usr_txt_verification_code: string | null,
    public date_deleted_at: Date | null,
  ) {}
}
